version: 2.1

orbs:
  node: circleci/node@1.1.6

jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run compile
            - run: npm install --production
            - persist_to_workspace:
                root: ~/project
                paths:
                  - index.js
                  - node_modules
                  - src
  deploy:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/repo
    steps:
      - checkout
      - run: sudo apt-get -y update
      - run: which aws || pip install --user awscli
      - run:
          name: Setup AWS CLI
          command: |
              mkdir -p $HOME/.aws
              echo [default] | tee -a $HOME/.aws/config
              echo region=ap-northeast-1|tee -a $HOME/.aws/config
      - attach_workspace:
          at: ~/project
      - run: make deploy

workflows:
    build-and-test:
      jobs:
        - build-and-test
        - deploy:
            requires:
              - build-and-test
            filters:
                branches:
                    only: master
