version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run compile
            - run: npm install --production
            - persist_to_workspace:
                root: ~/repo
                paths:
                  - index.js
                  - node_modules
                  - src
 deploy:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/repo
    steps:
      - checkout
      - run: sudo apt-get -y update
      - run:
          name: Install some libraries
          command: |
              which aws || pip install --user awscli
      - attach_workspace:
          at: ~/repo

      - deploy:
          name: Deploy Production
          command: |
              make deploy
workflows:
    build-and-test:
      jobs:
        - build-and-test
        - deploy:
            filters:
              branches:
                only: master
