version: 2.1
orbs:
  node: circleci/node@2.0.2
jobs:
  build-and-test:
    working_directory: ~/repo
    docker:
      # https://circleci.com/docs/ja/2.0/docker-image-tags.json
      - image: circleci/node:12.14.0
    steps:
      - checkout
      - node/install-packages
      - npm run compile
workflows:
    build-and-test:
      jobs:
        - build-and-test
