version: 2.1
jobs:
  build-and-test:
    working_directory: ~/repo
    docker:
      # https://circleci.com/docs/ja/2.0/docker-image-tags.json
      - image: circleci/node:12.14.0
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
workflows:
    build-and-test:
      jobs:
        - build-and-test
